<?php
$exercise = [
    'Sumo Squats' => '10',
    'Push Ups' => '10',
    'Lunges' => '10',
    'Jump Squats' => '10',
    'Plank' => '10',
    'Jumping Jacks' => '10',
    'Calf Raises' => '10',
    'Pistol Squat' => '10',
    'Reverse Lunges' => '10',
    'Spiderman Moutain Climbers' => '10',
    'Standing Oblique Crunches' => '10',
    'Curtsy Lunges With Side Kick' => '10',
    'Wide-Grip Push-Ups' => '10',
    'Crab Walk' => '10',
    'Froggers' => '10',
    'High Knees' => '10',
    'Plank Jacks' => '10',
    'Side Lunges' => '10',
    'Side Step Squats' => '10',
    'Forward to Reverse Lunges' => '10',
    'Plank Ups' => '10',
    'Squat Jacks' => '10',
    'Groiners' => '10',
    'Burpeess' => '10',
    'Trunk Rotations' => '10',
    'Single-Leg Kickbacks' => '10',
    'Bicycle Crunches' => '10',
    'Overhead Crunchs' => '10',
    'Plank Taps' => '10',
    'Alternating Knee-To-Chests' => '10',
    'Single-Leg Walkout to Push-Ups' => '10',
    'Diamond Push-Ups' => '10',
    'Bird Dog Crunches' => '10',
    'Down Dog Abs' => '10',
    'Side Plank Dips' => '10',
    'Mountain Climbers' => '10',
    'Plank Hops' => '10',
    'Side Plank Rotation With Kicks' => '10',
    'V-Ups' => '10',
    'Dead Bugs' => '10',
    'Sit-Ups To Twists' => '10',
    'Jumping Lunges' => '10',
    'Spider Crawls' => '10',
    'Supermans' => '10',
    'Glute kickbacks' => '10',
    'Oblique crunchs' => '10',
    'Frozen V-sits' => '10',
    'Chest Flick Press-Ups' => '10',
    ];

$keys = array_keys($exercise);
$random = $keys[array_rand($keys, 1)];
echo $random . " " . $exercise[$random]  . " reps";
?>